apiVersion: v1
kind: ServiceAccount
metadata:
  name: launchpad-backend
  labels:
    app.kubernetes.io/part-of: partner-ai-launchpad
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"launchpad-api"}}'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: launchpad-portal
  labels:
    app.kubernetes.io/part-of: partner-ai-launchpad
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"launchpad"}}'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: launchpad-admin
  labels:
    app.kubernetes.io/part-of: partner-ai-launchpad
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"launchpad-admin"}}'
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-oauth-cookie
type: Opaque
stringData:
  cookie-secret: GENERATE-RANDOM-SECRET-BACKEND
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-oauth-cookie
type: Opaque
stringData:
  cookie-secret: GENERATE-RANDOM-SECRET-PORTAL
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-oauth-cookie
type: Opaque
stringData:
  cookie-secret: GENERATE-RANDOM-SECRET-ADMIN
