apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: launchpad-flightpath-candidate

resources:
  - ../../base
  - ../../../../catalog
  - candidate-clusters.yaml
  - candidate-rbac.yaml
  - candidate-maas.yaml
  - public-access-ha.yaml

configMapGenerator:
  - name: flightpath-candidate-serve-llms-catalog
    files:
      - catalog-item.yaml=intel-llm-cpu-serving.catalog-item.yaml
  - name: flightpath-candidate-agent-201-catalog
    files:
      - catalog-item.yaml=intel-xeon6-agent-201.catalog-item.yaml
  - name: flightpath-candidate-multi-agent-catalog
    files:
      - catalog-item.yaml=multi-agent-quickstart.catalog-item.yaml
  - name: flightpath-candidate-hybrid-fraud-catalog
    files:
      - catalog-item.yaml=hybrid-fraud-detection.catalog-item.yaml
  - name: flightpath-candidate-network-operations-catalog
    files:
      - catalog-item.yaml=network-operations-agent.catalog-item.yaml
  - name: flightpath-candidate-agent-reliability-catalog
    files:
      - catalog-item.yaml=agent-reliability.catalog-item.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: backend
    newName: ghcr.io/rhpds/launchpad-backend
    digest: sha256:c5d74d8ce213ea6334227fd5d010f58168011283ee246de9f458f2165e51beef
  - name: partner-portal
    newName: ghcr.io/rhpds/launchpad-portal
    digest: sha256:f6778b456d7e737fd5483f3338205c15b5003faa475fafb1ecdb712c6928c9d1
  - name: admin
    newName: ghcr.io/rhpds/launchpad-admin
    digest: sha256:9808230f3ad7686a1f3413004ef24f0d3eabf33a71243252b6368dcc643c44ce
  - name: postgres
    newName: docker.io/library/postgres
    digest: sha256:075f7ba66bc9b3ce7d6b8b635208ff61cd7cf1a67d71ec530eec5d7ae0cbe571
  - name: registry.redhat.io/openshift4/ose-oauth-proxy
    newName: registry.redhat.io/openshift4/ose-oauth-proxy
    digest: sha256:e68637bc28cd2e0820d75650ed3019b64247d9b2760e455bf6c1af7d5d66b7af
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newName: quay.io/oauth2-proxy/oauth2-proxy
    digest: sha256:786bed0f000c0f8a7b31619244ebab02406a8856a4faf3f5fb1df61fbd6c30ed

patches:
  - path: patch-configmap.yaml
  - path: patch-routes.yaml
  - path: patch-postgres-pvc.yaml
  - path: patch-generated-secrets.yaml
  - path: patch-remove-shared-rbac.yaml
  - path: patch-runtime.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: partner-ai-launchpad
      launchpad.redhat.com/environment: flightpath-candidate
    includeSelectors: false
