apiVersion: v1
kind: Service
metadata:
  name: solution-tools
spec:
  selector:
    launchpad.redhat.com/solution-stack: agent-201
  ports:
    - port: 8095
      targetPort: 8095
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tools
  annotations:
    haproxy.router.openshift.io/timeout: 60s
spec:
  to:
    kind: Service
    name: solution-tools
  port:
    targetPort: 8095
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
