apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: partner-ai-launchpad

resources:
  - ../../base

patches:
  - path: patch-routes.yaml
  - path: patch-configmap.yaml

images:
  - name: backend
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-backend
    newTag: latest
  - name: partner-portal
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-portal
    newTag: latest
  - name: admin
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-admin
    newTag: latest
