apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: partner-ai-launchpad

resources:
  - ../../base

images:
  - name: backend
    newName: registry.CLUSTER_DOMAIN/partner-ai-launchpad/backend
    newTag: latest
  - name: partner-portal
    newName: registry.CLUSTER_DOMAIN/partner-ai-launchpad/partner-portal
    newTag: latest
  - name: admin
    newName: registry.CLUSTER_DOMAIN/partner-ai-launchpad/admin
    newTag: latest
