apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: launchpad-arena
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/launchpad.git
    targetRevision: main
    path: deploy/launchpad/overlays/arena-argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: partner-ai-launchpad
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
