apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: partner-ai-launchpad

resources:
  - ../../base
  - buildconfig.yaml
  - operations-automation.yaml
  - reliability.yaml
  - arena-clusters.yaml

patches:
  - path: patch-routes.yaml
  - path: patch-configmap.yaml
  - path: patch-postgres-pvc.yaml
  - path: patch-runtime.yaml
  - path: patch-generated-secrets.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
    path: patch-backend-no-oauth.yaml

images:
  - name: backend
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-backend
    digest: sha256:28f1bda8ef5b3e5d32b6b79b2af8f714685fe7503859f61b08115e1f1ca5d690
  - name: partner-portal
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-portal
    newTag: latest
  - name: admin
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-admin
    newTag: latest
