apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: partner-ai-launchpad

resources:
  - ../../base
  - buildconfig.yaml
  - operations-automation.yaml
  - reliability.yaml
  - arena-clusters.yaml

patches:
  - path: patch-routes.yaml
  - path: patch-configmap.yaml
  - path: patch-postgres-pvc.yaml
  - path: patch-runtime.yaml
  - path: patch-generated-secrets.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
    path: patch-backend-no-oauth.yaml

images:
  - name: backend
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-backend
    digest: sha256:391e8ae6228aef06d11efd0fcd3da4f485e8cd40b1ad9da52887ff7ace8a80ed
  - name: partner-portal
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-portal
    newTag: latest
  - name: admin
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-admin
    newTag: latest
