$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: launchpad-db-secret
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: backend-oauth-cookie
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: portal-oauth-cookie
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: admin-oauth-cookie

