clusters:
  - cluster_id: arena
    display_name: Arena CPU Execution
    api_url: https://kubernetes.default.svc
    ingress_domain: apps.arena.fm2aihpcsed.com
    console_url: https://console-openshift-console.apps.arena.fm2aihpcsed.com
    storage_class: launchpad-nfs-ephemeral
    local: true
    priority: 10
    public_access_enabled: true
    public_ingress_domain: trycloudflare.com
    capabilities: [cpu, openshift, operators, openshift-ai, rhoai, showroom, model_endpoint, embedding_endpoint, mlflow, openshift_logging, agentops_observability_stack, user_workload_monitoring, data_science_pipelines, control-plane]
    service_urls:
      mlflow: https://rh-ai.apps.arena.fm2aihpcsed.com/mlflow
      rhoai: https://rh-ai.apps.arena.fm2aihpcsed.com/
    model_endpoints:
      granite-2b-cpu: http://ovms-granite-2b.fleet-llm-d.svc:8080/v1
      granite-3.2-8b-tools: http://vllm-granite-3-2-8b-tools.fleet-llm-d.svc:8080/v1
      nomic-embed-text-v1.5: http://tei-nomic-embed.fleet-llm-d.svc:8080/v1
