apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: inference-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-frontend
  template:
    metadata:
      labels:
        app: inference-frontend
    spec:
      containers:
        - name: frontend
          image: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/inference-frontend:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
